export const ROUTES = {
  OVERVIEW: '/',
  APPLICATIONS: '/applications',
  EVENTS: '/events',
  TEMPLATES: '/templates',
  RULES: '/rules',
  DEVICES: '/devices',
  PUBLISHER: '/publisher',
  AUTOMATION_ONE_TIME: '/automation/one-time',
  AUTOMATION_RECURRING: '/automation/recurring',
  AUTOMATION_CONDITIONS: '/automation/conditions',
  NOTIFICATIONS: '/notifications',
  NOTIFICATION_LOGS: '/notification-logs',
  OPERATIONS_QUEUE: '/operations/queue',
  OPERATIONS_METRICS: '/operations/metrics',
  OPERATIONS_WORKERS: '/operations/workers',
  OPERATIONS_HEALTH: '/operations/health',
  SETTINGS: '/settings',
};
